version: "3.9"

services:
  db:
    image: postgres:13
    container_name: harmony-db
    environment:
      POSTGRES_USER: harmony_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: harmony_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - harmony_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: harmony-backend
    environment:
      DATABASE_URL: postgres://harmony_user:password@db:5432/harmony_db
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - harmony_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: harmony-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - harmony_network

volumes:
  postgres_data:

networks:
  harmony_network:

