name: Run Backend Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Create missing assets directory
        run: |
          mkdir -p frontend/assets
          touch frontend/assets/.gitkeep

      - name: Ensure docker-compose.yml is in place
        run: |
          mv docker-compose.yml backend/docker-compose.yml || true

      - name: Start all Docker containers
        run: docker-compose up -d

      - name: Wait for Database
        run: sleep 10

      - name: Install Dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          cd backend
          pytest tests/
